# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A compiler for Fay, a Haskell subset that compiles to JavaScript."
HOMEPAGE="http://fay-lang.org/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86 ~x64-macos ~x86-macos"
IUSE=""

RDEPEND="dev-haskell/aeson[profile?]
		dev-haskell/attoparsec[profile?]
		dev-haskell/data-default[profile?]
		dev-haskell/groom[profile?]
		dev-haskell/haskeline[profile?]
		dev-haskell/haskell-src-exts[profile?]
		dev-haskell/language-ecmascript[profile?]
		dev-haskell/mtl[profile?]
		dev-haskell/options[profile?]
		dev-haskell/pretty-show[profile?]
		dev-haskell/safe[profile?]
		dev-haskell/syb[profile?]
		dev-haskell/text[profile?]
		dev-haskell/unordered-containers[profile?]
		dev-haskell/utf8-string[profile?]
		dev-haskell/vector[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
