# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A compiler for Fay, a Haskell subset that compiles to JavaScript."
HOMEPAGE="http://fay-lang.org/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/blaze-html[profile?]
		dev-haskell/blaze-markup[profile?]
		dev-haskell/data-default[profile?]
		dev-haskell/haskell-src-exts[profile?]
		dev-haskell/hunit[profile?]
		dev-haskell/json[profile?]
		dev-haskell/language-javascript[profile?]
		dev-haskell/mtl[profile?]
		dev-haskell/pretty-show[profile?]
		dev-haskell/safe[profile?]
		dev-haskell/time[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
